apiVersion: v1
kind: Service
metadata:
  name: devops-app
spec:
  selector:
    app: devops-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 31920
  type: NodePort
